#pragma once
// generated by apexdumper
// [Miscellaneous]
constexpr char OFF_GAME_VERSION[] = "v3.0.82.42"; //[Miscellaneous]->GameVersion
constexpr uint64_t OFF_ENTITY_LIST = 0x1f62278; //[Miscellaneous]->cl_entitylist
constexpr uint64_t OFF_LOCAL_ENTITY_HANDLE = 0x1767248; //[Miscellaneous]->LocalEntityHandle
constexpr uint64_t OFF_LOCAL_PLAYER = 0x24354f8; //[Miscellaneous]->LocalPlayer
constexpr uint64_t OFF_GLOBAL_VARS = 0x1836330; //[Miscellaneous]->GlobalVars
constexpr uint64_t OFF_NAME_LIST = 0xd427360; //[Miscellaneous]->NameList
constexpr uint64_t OFF_VIEW_RENDER = 0x76e9ab8; //[Miscellaneous]->ViewRender
constexpr uint64_t OFF_VIEW_MATRIX = 0x11a350; //[Miscellaneous]->ViewMatrix
constexpr uint64_t OFF_LEVEL_NAME = 0x1836670 + 0x01c4; //[Miscellaneous]->ClientState + 0x01c4
constexpr uint64_t OFF_PROJECTILE_SPEED = 0x04ec + 0x19d8; //[Miscellaneous]->CWeaponX!m_flProjectileSpeed //[WeaponSettings]->projectile_launch_speed + [WeaponSettingsMeta]->base
constexpr uint64_t OFF_PROJECTILE_SCALE = OFF_PROJECTILE_SPEED + 0x8; //[Miscellaneous]->CWeaponX!m_flProjectileScale //[WeaponSettings]->projectile_gravity_scale + [WeaponSettingsMeta]->base
constexpr uint64_t OFF_CAMERA_ORIGIN = 0x1ee0; //[Miscellaneous]->CPlayer!camera_origin
constexpr uint64_t OFF_STUDIO_HDR = 0x1000; //[Miscellaneous]->CBaseAnimating!m_pStudioHdr
// [RecvTable.DT_BaseAnimating]
constexpr uint64_t OFF_BONE = 0x0db0 + 0x48; //[RecvTable.DT_BaseAnimating]->m_nForceBone + 0x48
// [RecvTable.DT_BaseCombatCharacter]
constexpr uint64_t OFF_WEAPON_HANDLE = 0x1944; //[RecvTable.DT_BaseCombatCharacter]->m_latestPrimaryWeapons
constexpr uint64_t OFF_GRENADE_HANDLE = 0x1954; //[RecvTable.DT_BaseCombatCharacter]->m_latestNonOffhandWeapons
constexpr uint64_t OFF_LAST_VISIBLE_TIME = 0x19a0; //[Miscellaneous]->CPlayer!lastVisibleTime //[RecvTable.DT_BaseCombatCharacter]->m_hudInfo_visibilityTestAlwaysPasses + 0x2
constexpr uint64_t OFF_LAST_AIMEDAT_TIME = 0x19a8; //[Miscellaneous]->CWeaponX!lastCrosshairTargetTime //[RecvTable.DT_BaseCombatCharacter]->m_hudInfo_visibilityTestAlwaysPasses + 0x2 + 0x8
// [RecvTable.DT_BaseEntity]
constexpr uint64_t OFF_SHIELD = 0x01a0; //[RecvTable.DT_BaseEntity]->m_shieldHealth
constexpr uint64_t OFF_TEAM_NUMBER = 0x0338; //[RecvTable.DT_BaseEntity]->m_iTeamNum
constexpr uint64_t OFF_SQUAD_ID = 0x0344; //[RecvTable.DT_BaseEntity]->m_squadID
constexpr uint64_t OFF_NAME = 0x0481; //[RecvTable.DT_BaseEntity]->m_iName
constexpr uint64_t OFF_NAME_INDEX = 0x38; //[RecvTable.DT_BaseEntity]
// [RecvTable.DT_LocalPlayerExclusive]
constexpr uint64_t OFF_TRAVERSAL_PROGRESS = 0x2b6c; //[RecvTable.DT_LocalPlayerExclusive]->m_traversalProgress
constexpr uint64_t OFF_TRAVERSAL_START_TIME = 0x2b70; //[RecvTable.DT_LocalPlayerExclusive]->m_traversalStartTime
// [RecvTable.DT_Player]
constexpr uint64_t OFF_HEALTH = 0x0328; //[RecvTable.DT_Player]->m_iHealth
constexpr uint64_t OFF_LIFE_STATE = 0x0690; //[RecvTable.DT_Player]->m_lifeState
constexpr uint64_t OFF_BLEEDOUT_STATE = 0x2760; //[RecvTable.DT_Player]->m_bleedoutState
constexpr uint64_t OFF_XP_LEVEL = 0x3784; //[RecvTable.DT_Player]->m_xp
// [RecvTable.DT_PropSurvival]
constexpr uint64_t OFF_SIGNIFIER_NAME = 0x0478; //[RecvTable.DT_PropSurvival]->m_iSignifierName
constexpr uint64_t OFF_ITEM_HANDLE = 0x1568; //[RecvTable.DT_PropSurvival]->m_customScriptInt
// [RecvTable.DT_WeaponX]
constexpr uint64_t OFF_WEAPON_INDEX = 0x1788; //[RecvTable.DT_WeaponX]->m_weaponNameIndex
// [DataMap.C_BaseEntity]
constexpr uint64_t OFF_LOCAL_ORIGIN = 0x017c; //[DataMap.C_BaseEntity]->m_vecAbsOrigin
// [DataMap.C_Player]
constexpr uint64_t OFF_ZOOMING = 0x1be1; //[DataMap.C_Player]->m_bZooming
constexpr uint64_t OFF_TIME_BASE = 0x2088; //[DataMap.C_Player]->m_currentFramePlayer.timeBase
constexpr uint64_t OFF_YAW = 0x223c - 0x8; //[DataMap.C_Player]->m_currentFramePlayer.m_ammoPoolCount - 0x8
constexpr uint64_t OFF_VIEW_ANGLES = 0x2534 - 0x14; //[DataMap.C_Player]->m_ammoPoolCapacity - 0x14
// [DataMap.WeaponPlayerData]
constexpr uint64_t OFF_ZOOM_FOV = 0x15e0 + 0x00bc; //[RecvTable.DT_WeaponX]->m_playerData + [DataMap.WeaponPlayerData]->m_targetZoomFOV
// [ConVars]
constexpr uint64_t OFF_GAME_MODE = 0x0246d6a0; //[ConVars]->mp_gamemode

// [Static]
inline uint64_t OFF_REGION = 0x140000000; //[Static]->Region
// [IDA]
constexpr uint64_t OFF_OBSERVER_LIST = 0x01f621d0 + 0x20c8; //[ConVars]->gamepad_aim_assist_melee + 0x20c8 //IDA signature >> [48 8B 0D ? ? ? ? 48 85 C9 74 ? 48 8B 01 FF ? ? 48 85 C0 74 ? 48 63 4E 38]
constexpr uint64_t OFF_OBSERVER_ARRAY = 0x0974; //[RecvTable.DT_GlobalNonRewinding]->m_gameTimescale //IDA signature >> [8B 84 C8 ? ? ? ? 83 F8]

constexpr uint64_t HIGHLIGHT_TYPE_SIZE = 0x34;
constexpr uint64_t OFF_GLOW_THROUGH_WALL = 0x26c; //[DT_HighlightSettings].?
constexpr uint64_t OFF_GLOW_FIX = 0x268;
constexpr uint64_t OFF_GLOW_HIGHLIGHT_ID = 0x29C; //[DT_HighlightSettings].m_highlightServerActiveStates
constexpr uint64_t OFF_GLOW_HIGHLIGHTS = 0xb1db5a0;
constexpr uint64_t OFF_GLOW_ENABLE = 0x28c;